### ISSUE TITLE
Any chance of updating to support Julia v1 and remove support of 0.7?

### ISSUE THREAD

**Issue by xiaodaigh** [FNj/Hose.jl#5]
If easy, I might have a crack.

**Comment by xiaodaigh** [comment]
If I submit a PR will you accept it?

**Comment by FNj** [comment]
Sure, I gladly will. @xiaodaigh

**Comment by xiaodaigh** [comment]
fixed by #7

**Comment by xiaodaigh** [comment]
@FNj I have done that in #7. when do you have time to take a look?

**Comment by FNj** [comment]
@xiaodaigh It's done.
